//! Keybindings for non-search, non-job screens.
//!
//! Responsibilities:
//! - Define bindings for list/detail screens like indexes, apps, users, and settings.
//!
//! Non-responsibilities:
//! - Resolving input events or mutating App state.
//!
//! Invariants:
//! - Ordering matches the rendered help/docs expectations.

use crossterm::event::{KeyCode, KeyModifiers};

use crate::action::Action;
use crate::app::CurrentScreen;

use super::super::{BindingScope, Keybinding, Matcher, Section};

pub(super) fn bindings() -> Vec<Keybinding> {
    use CurrentScreen::*;

    vec![
        // Indexes
        Keybinding {
            section: Section::Indexes,
            keys: "r",
            description: "Refresh indexes",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadIndexes),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "e",
            description: "Export indexes",
            scope: BindingScope::Screen(Indexes),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "Ctrl+c",
            description: "Copy selected index name",
            scope: BindingScope::Screen(Indexes),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Cluster
        Keybinding {
            section: Section::Cluster,
            keys: "r",
            description: "Refresh cluster info",
            scope: BindingScope::Screen(Cluster),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadClusterInfo),
            handles_input: true,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "e",
            description: "Export cluster info",
            scope: BindingScope::Screen(Cluster),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "Ctrl+c",
            description: "Copy cluster ID",
            scope: BindingScope::Screen(Cluster),
            matcher: None,
            action: None,
            handles_input: false,
        },
        // Health
        Keybinding {
            section: Section::Health,
            keys: "r",
            description: "Refresh health status",
            scope: BindingScope::Screen(Health),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadHealth),
            handles_input: true,
        },
        Keybinding {
            section: Section::Health,
            keys: "e",
            description: "Export health info",
            scope: BindingScope::Screen(Health),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Health,
            keys: "Ctrl+c",
            description: "Copy health status",
            scope: BindingScope::Screen(Health),
            matcher: None,
            action: None,
            handles_input: false,
        },
        // Saved Searches
        Keybinding {
            section: Section::SavedSearches,
            keys: "r",
            description: "Refresh saved searches",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadSavedSearches),
            handles_input: true,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "e",
            description: "Export saved searches",
            scope: BindingScope::Screen(SavedSearches),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "Ctrl+c",
            description: "Copy selected saved search name",
            scope: BindingScope::Screen(SavedSearches),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "Enter",
            description: "Run selected search",
            scope: BindingScope::Screen(SavedSearches),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Internal Logs
        Keybinding {
            section: Section::InternalLogs,
            keys: "r",
            description: "Refresh logs",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadInternalLogs),
            handles_input: true,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "e",
            description: "Export logs",
            scope: BindingScope::Screen(InternalLogs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "a",
            description: "Toggle auto-refresh",
            scope: BindingScope::Screen(InternalLogs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "Ctrl+c",
            description: "Copy selected log message",
            scope: BindingScope::Screen(InternalLogs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Apps
        Keybinding {
            section: Section::Apps,
            keys: "r",
            description: "Refresh apps",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadApps),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "e",
            description: "Export apps",
            scope: BindingScope::Screen(Apps),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Apps,
            keys: "Ctrl+c",
            description: "Copy selected app name",
            scope: BindingScope::Screen(Apps),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Apps,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Users
        Keybinding {
            section: Section::Users,
            keys: "r",
            description: "Refresh users",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadUsers),
            handles_input: true,
        },
        Keybinding {
            section: Section::Users,
            keys: "e",
            description: "Export users",
            scope: BindingScope::Screen(Users),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Users,
            keys: "Ctrl+c",
            description: "Copy selected username",
            scope: BindingScope::Screen(Users),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Users,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Users,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Users,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Users,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Settings
        Keybinding {
            section: Section::Settings,
            keys: "t",
            description: "Cycle theme",
            scope: BindingScope::Screen(Settings),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('t'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::CycleTheme),
            handles_input: true,
        },
        Keybinding {
            section: Section::Settings,
            keys: "a",
            description: "Toggle auto-refresh",
            scope: BindingScope::Screen(Settings),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "s",
            description: "Cycle sort column",
            scope: BindingScope::Screen(Settings),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "d",
            description: "Toggle sort direction",
            scope: BindingScope::Screen(Settings),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "c",
            description: "Clear search history",
            scope: BindingScope::Screen(Settings),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "r",
            description: "Reload settings",
            scope: BindingScope::Screen(Settings),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::SwitchToSettings),
            handles_input: true,
        },
    ]
}
