//! Keybindings for non-search, non-job screens.
//!
//! Responsibilities:
//! - Define bindings for list/detail screens like indexes, apps, users, and settings.
//!
//! Non-responsibilities:
//! - Resolving input events or mutating App state.
//!
//! Invariants:
//! - Ordering matches the rendered help/docs expectations.

use crossterm::event::{KeyCode, KeyModifiers};

use crate::action::Action;
use crate::app::CurrentScreen;

use super::super::{BindingScope, Keybinding, Matcher, Section};

pub(super) fn bindings() -> Vec<Keybinding> {
    use CurrentScreen::*;

    vec![
        // Indexes
        Keybinding {
            section: Section::Indexes,
            keys: "r",
            description: "Refresh indexes",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadMoreIndexes),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "Enter",
            description: "View index details",
            scope: BindingScope::Screen(Indexes),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "Ctrl+e",
            description: "Export indexes",
            scope: BindingScope::Screen(Indexes),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "Ctrl+c",
            description: "Copy selected index name",
            scope: BindingScope::Screen(Indexes),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "c",
            description: "Create new index",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('c'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::OpenCreateIndexDialog),
            handles_input: true,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "m",
            description: "Modify selected index",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('m'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled by input handler
            handles_input: false,
        },
        Keybinding {
            section: Section::Indexes,
            keys: "d",
            description: "Delete selected index",
            scope: BindingScope::Screen(Indexes),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('d'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled by input handler
            handles_input: false,
        },
        // Cluster
        Keybinding {
            section: Section::Cluster,
            keys: "r",
            description: "Refresh cluster info",
            scope: BindingScope::Screen(Cluster),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadClusterInfo),
            handles_input: true,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "p",
            description: "Toggle peers view",
            scope: BindingScope::Screen(Cluster),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('p'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::ToggleClusterViewMode),
            handles_input: true,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "j/k or Up/Down",
            description: "Navigate peers list",
            scope: BindingScope::Screen(Cluster),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "j/k or Up/Down",
            description: "Navigate peers list",
            scope: BindingScope::Screen(Cluster),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "j/k or Up/Down",
            description: "Navigate peers list",
            scope: BindingScope::Screen(Cluster),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "j/k or Up/Down",
            description: "Navigate peers list",
            scope: BindingScope::Screen(Cluster),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "Ctrl+e",
            description: "Export cluster info",
            scope: BindingScope::Screen(Cluster),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Cluster,
            keys: "Ctrl+c",
            description: "Copy cluster ID",
            scope: BindingScope::Screen(Cluster),
            matcher: None,
            action: None,
            handles_input: false,
        },
        // Health
        Keybinding {
            section: Section::Health,
            keys: "r",
            description: "Refresh health status",
            scope: BindingScope::Screen(Health),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadHealth),
            handles_input: true,
        },
        Keybinding {
            section: Section::Health,
            keys: "Ctrl+e",
            description: "Export health info",
            scope: BindingScope::Screen(Health),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Health,
            keys: "Ctrl+c",
            description: "Copy health status",
            scope: BindingScope::Screen(Health),
            matcher: None,
            action: None,
            handles_input: false,
        },
        // License
        Keybinding {
            section: Section::License,
            keys: "r",
            description: "Refresh license info",
            scope: BindingScope::Screen(License),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadLicense),
            handles_input: true,
        },
        Keybinding {
            section: Section::License,
            keys: "Ctrl+e",
            description: "Export license info",
            scope: BindingScope::Screen(License),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::License,
            keys: "Ctrl+c",
            description: "Copy license summary",
            scope: BindingScope::Screen(License),
            matcher: None,
            action: None,
            handles_input: false,
        },
        // KVStore
        Keybinding {
            section: Section::Kvstore,
            keys: "r",
            description: "Refresh KVStore status",
            scope: BindingScope::Screen(Kvstore),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadKvstore),
            handles_input: true,
        },
        Keybinding {
            section: Section::Kvstore,
            keys: "Ctrl+e",
            description: "Export KVStore status",
            scope: BindingScope::Screen(Kvstore),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Kvstore,
            keys: "Ctrl+c",
            description: "Copy KVStore status",
            scope: BindingScope::Screen(Kvstore),
            matcher: None,
            action: None,
            handles_input: false,
        },
        // Saved Searches
        Keybinding {
            section: Section::SavedSearches,
            keys: "r",
            description: "Refresh saved searches",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadSavedSearches),
            handles_input: true,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "Ctrl+e",
            description: "Export saved searches",
            scope: BindingScope::Screen(SavedSearches),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "Ctrl+c",
            description: "Copy selected saved search name",
            scope: BindingScope::Screen(SavedSearches),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "Enter",
            description: "Run selected search",
            scope: BindingScope::Screen(SavedSearches),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::SavedSearches,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SavedSearches),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Internal Logs
        Keybinding {
            section: Section::InternalLogs,
            keys: "r",
            description: "Refresh logs",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadMoreInternalLogs),
            handles_input: true,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "Ctrl+e",
            description: "Export logs",
            scope: BindingScope::Screen(InternalLogs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "a",
            description: "Toggle auto-refresh",
            scope: BindingScope::Screen(InternalLogs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "Ctrl+c",
            description: "Copy selected log message",
            scope: BindingScope::Screen(InternalLogs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::InternalLogs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(InternalLogs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Apps
        Keybinding {
            section: Section::Apps,
            keys: "r",
            description: "Refresh apps",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadMoreApps),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "Ctrl+e",
            description: "Export apps",
            scope: BindingScope::Screen(Apps),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Apps,
            keys: "Ctrl+c",
            description: "Copy selected app name",
            scope: BindingScope::Screen(Apps),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Apps,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Apps,
            keys: "e",
            description: "Enable selected app",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('e'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled directly in input handler
            handles_input: false,
        },
        Keybinding {
            section: Section::Apps,
            keys: "d",
            description: "Disable selected app",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('d'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled directly in input handler
            handles_input: false,
        },
        Keybinding {
            section: Section::Apps,
            keys: "i",
            description: "Install app from .spl file",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('i'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled directly in input handler
            handles_input: false,
        },
        Keybinding {
            section: Section::Apps,
            keys: "x",
            description: "Remove selected app",
            scope: BindingScope::Screen(Apps),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('x'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled directly in input handler
            handles_input: false,
        },
        // Users
        Keybinding {
            section: Section::Users,
            keys: "r",
            description: "Refresh users",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadMoreUsers),
            handles_input: true,
        },
        Keybinding {
            section: Section::Users,
            keys: "Ctrl+e",
            description: "Export users",
            scope: BindingScope::Screen(Users),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Users,
            keys: "Ctrl+c",
            description: "Copy selected username",
            scope: BindingScope::Screen(Users),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Users,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Users,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Users,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Users,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Users),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Search Peers
        Keybinding {
            section: Section::SearchPeers,
            keys: "r",
            description: "Refresh search peers",
            scope: BindingScope::Screen(SearchPeers),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadSearchPeers {
                count: 30,
                offset: 0,
            }),
            handles_input: true,
        },
        Keybinding {
            section: Section::SearchPeers,
            keys: "Ctrl+e",
            description: "Export search peers",
            scope: BindingScope::Screen(SearchPeers),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::SearchPeers,
            keys: "Ctrl+c",
            description: "Copy selected peer name",
            scope: BindingScope::Screen(SearchPeers),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::SearchPeers,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SearchPeers),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::SearchPeers,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SearchPeers),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::SearchPeers,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SearchPeers),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::SearchPeers,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(SearchPeers),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Configs
        Keybinding {
            section: Section::Configs,
            keys: "r",
            description: "Refresh config files",
            scope: BindingScope::Screen(Configs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadConfigFiles),
            handles_input: true,
        },
        Keybinding {
            section: Section::Configs,
            keys: "/",
            description: "Search stanzas",
            scope: BindingScope::Screen(Configs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('/'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::EnterSearchMode),
            handles_input: true,
        },
        Keybinding {
            section: Section::Configs,
            keys: "Enter",
            description: "View stanza details",
            scope: BindingScope::Screen(Configs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Configs,
            keys: "h",
            description: "Go back",
            scope: BindingScope::Screen(Configs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Configs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Configs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Configs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Configs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Configs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Configs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Configs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Configs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Inputs
        Keybinding {
            section: Section::Inputs,
            keys: "r",
            description: "Refresh inputs",
            scope: BindingScope::Screen(Inputs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadMoreInputs),
            handles_input: true,
        },
        Keybinding {
            section: Section::Inputs,
            keys: "e",
            description: "Enable input",
            scope: BindingScope::Screen(Inputs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('e'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled by input handler
            handles_input: true,
        },
        Keybinding {
            section: Section::Inputs,
            keys: "d",
            description: "Disable input",
            scope: BindingScope::Screen(Inputs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('d'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled by input handler
            handles_input: true,
        },
        Keybinding {
            section: Section::Inputs,
            keys: "Ctrl+c",
            description: "Copy selected input name",
            scope: BindingScope::Screen(Inputs),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Inputs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Inputs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Inputs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Inputs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Inputs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Inputs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Inputs,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Inputs),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Settings
        Keybinding {
            section: Section::Settings,
            keys: "t",
            description: "Cycle theme",
            scope: BindingScope::Screen(Settings),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('t'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::CycleTheme),
            handles_input: true,
        },
        Keybinding {
            section: Section::Settings,
            keys: "a",
            description: "Toggle auto-refresh",
            scope: BindingScope::Screen(Settings),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "s",
            description: "Cycle sort column",
            scope: BindingScope::Screen(Settings),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "d",
            description: "Toggle sort direction",
            scope: BindingScope::Screen(Settings),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "c",
            description: "Clear search history",
            scope: BindingScope::Screen(Settings),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "r",
            description: "Reload settings",
            scope: BindingScope::Screen(Settings),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::SwitchToSettings),
            handles_input: true,
        },
        Keybinding {
            section: Section::Settings,
            keys: "p",
            description: "Switch profile",
            scope: BindingScope::Screen(Settings),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('p'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::OpenProfileSwitcher),
            handles_input: true,
        },
        Keybinding {
            section: Section::Settings,
            keys: "n",
            description: "Create new profile",
            scope: BindingScope::Screen(Settings),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('n'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::OpenCreateProfileDialog),
            handles_input: true,
        },
        Keybinding {
            section: Section::Settings,
            keys: "e",
            description: "Edit selected profile",
            scope: BindingScope::Screen(Settings),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('e'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled by input handler
            handles_input: false,
        },
        Keybinding {
            section: Section::Settings,
            keys: "x",
            description: "Delete selected profile",
            scope: BindingScope::Screen(Settings),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('x'),
                modifiers: KeyModifiers::NONE,
            }),
            action: None, // Handled by input handler
            handles_input: false,
        },
        // Overview
        Keybinding {
            section: Section::Overview,
            keys: "r",
            description: "Refresh overview",
            scope: BindingScope::Screen(Overview),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadOverview),
            handles_input: true,
        },
        Keybinding {
            section: Section::Overview,
            keys: "Ctrl+e",
            description: "Export overview",
            scope: BindingScope::Screen(Overview),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Overview,
            keys: "Ctrl+c",
            description: "Copy overview summary",
            scope: BindingScope::Screen(Overview),
            matcher: None,
            action: None,
            handles_input: false,
        },
        // Multi-Instance
        Keybinding {
            section: Section::MultiInstance,
            keys: "r",
            description: "Refresh multi-instance dashboard",
            scope: BindingScope::Screen(MultiInstance),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadMultiInstanceOverview),
            handles_input: true,
        },
        Keybinding {
            section: Section::MultiInstance,
            keys: "Ctrl+e",
            description: "Export multi-instance data",
            scope: BindingScope::Screen(MultiInstance),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::MultiInstance,
            keys: "Ctrl+c",
            description: "Copy instance summary",
            scope: BindingScope::Screen(MultiInstance),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::MultiInstance,
            keys: "j/k or Up/Down",
            description: "Navigate instances",
            scope: BindingScope::Screen(MultiInstance),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::MultiInstance,
            keys: "j/k or Up/Down",
            description: "Navigate instances",
            scope: BindingScope::Screen(MultiInstance),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::MultiInstance,
            keys: "j/k or Up/Down",
            description: "Navigate instances",
            scope: BindingScope::Screen(MultiInstance),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::MultiInstance,
            keys: "j/k or Up/Down",
            description: "Navigate instances",
            scope: BindingScope::Screen(MultiInstance),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Fired Alerts
        Keybinding {
            section: Section::FiredAlerts,
            keys: "r",
            description: "Refresh fired alerts",
            scope: BindingScope::Screen(FiredAlerts),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadFiredAlerts),
            handles_input: true,
        },
        Keybinding {
            section: Section::FiredAlerts,
            keys: "Ctrl+e",
            description: "Export fired alerts",
            scope: BindingScope::Screen(FiredAlerts),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::FiredAlerts,
            keys: "Ctrl+c",
            description: "Copy selected alert name",
            scope: BindingScope::Screen(FiredAlerts),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::FiredAlerts,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(FiredAlerts),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::FiredAlerts,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(FiredAlerts),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::FiredAlerts,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(FiredAlerts),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::FiredAlerts,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(FiredAlerts),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Forwarders
        Keybinding {
            section: Section::Forwarders,
            keys: "r",
            description: "Refresh forwarders",
            scope: BindingScope::Screen(Forwarders),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadForwarders {
                count: 30,
                offset: 0,
            }),
            handles_input: true,
        },
        Keybinding {
            section: Section::Forwarders,
            keys: "Ctrl+e",
            description: "Export forwarders",
            scope: BindingScope::Screen(Forwarders),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Forwarders,
            keys: "Ctrl+c",
            description: "Copy selected forwarder name",
            scope: BindingScope::Screen(Forwarders),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Forwarders,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Forwarders),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Forwarders,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Forwarders),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Forwarders,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Forwarders),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Forwarders,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Forwarders),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        // Lookups
        Keybinding {
            section: Section::Lookups,
            keys: "r",
            description: "Refresh lookup tables",
            scope: BindingScope::Screen(Lookups),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('r'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::LoadLookups {
                count: 30,
                offset: 0,
            }),
            handles_input: true,
        },
        Keybinding {
            section: Section::Lookups,
            keys: "Ctrl+e",
            description: "Export lookup tables",
            scope: BindingScope::Screen(Lookups),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Lookups,
            keys: "Ctrl+c",
            description: "Copy selected lookup name",
            scope: BindingScope::Screen(Lookups),
            matcher: None,
            action: None,
            handles_input: false,
        },
        Keybinding {
            section: Section::Lookups,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Lookups),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Lookups,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Lookups),
            matcher: Some(Matcher::Key {
                code: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
        Keybinding {
            section: Section::Lookups,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Lookups),
            matcher: Some(Matcher::Key {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateDown),
            handles_input: true,
        },
        Keybinding {
            section: Section::Lookups,
            keys: "j/k or Up/Down",
            description: "Navigate list",
            scope: BindingScope::Screen(Lookups),
            matcher: Some(Matcher::Key {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
            }),
            action: Some(Action::NavigateUp),
            handles_input: true,
        },
    ]
}
