# Purpose: Human-readable help output for the local development interface.
# Responsibilities: Document supported targets and knobs in one authoritative place.
# Scope: Imported by the workspace root Makefile.
# Usage: Run `make help`.
# Invariants/Assumptions: Help output reflects the current local-first contract and excludes removed container orchestration surface.

help:
	@echo "Splunk TUI - Available targets:"
	@echo ""
	@echo "  make bootstrap        - Check local prerequisites and optional accelerators"
	@echo "  make deps             - Fetch all dependencies (locked)"
	@echo "  make install          - Build + install supported binaries to $(INSTALL_DIR)"
	@echo "  make update           - Update all dependencies to latest stable versions"
	@echo "  make format           - Format code with rustfmt (write mode)"
	@echo "  make format-check     - Verify rustfmt formatting"
	@echo "  make lint             - Clippy autofix + strict check + format check"
	@echo "  make lint-fix         - Clippy autofix only (mutating)"
	@echo "  make lint-check       - Clippy strict check + format check (non-mutating)"
	@echo "  make fix              - Apply formatting + clippy autofix"
	@echo "  make type-check       - Type check the workspace (cargo check)"
	@echo "  make clean            - Remove build artifacts (keeps Cargo.lock)"
	@echo "  make test             - Run all tests (workspace, libs/bins/tests only)"
	@echo "  make test-all         - Alias for make test"
	@echo "  make test-unit        - Run unit tests (lib and bins)"
	@echo "  make test-integration - Run integration tests"
	@echo "  make test-smoke       - Run deterministic smoke suite for local validation"
	@echo "  make test-chaos       - Run chaos engineering tests"
	@echo "  make test-live        - Run live tests (LIVE_TESTS_MODE=required|optional|skip)"
	@echo "  make test-live-manual - Run manual live server test script"
	@echo "  make tui-smoke        - Run TUI UX smoke tests (snapshot suite, fast feedback)"
	@echo "  make tui-visual       - Run style-aware visual tests + interaction render checks"
	@echo "  make tui-accessibility - Run theme contrast/accessibility checks"
	@echo "  make run-tui          - Run TUI locally for manual testing"
	@echo "  make bench            - Run all benchmarks"
	@echo "  make bench-client     - Run client crate benchmarks"
	@echo "  make bench-cli        - Run CLI crate benchmarks"
	@echo "  make bench-tui        - Run TUI crate benchmarks"
	@echo "  make build            - Build supported runtime binaries (no install)"
	@echo "  make install-bins     - Install pre-built runtime binaries to $(INSTALL_DIR)"
	@echo "  make release          - Build + install supported binaries to $(INSTALL_DIR)"
	@echo "  make generate         - Regenerate derived docs (internal docs tool)"
	@echo "  make lint-docs        - Verify docs are up to date"
	@echo "  make lint-secrets     - Run secret-commit guard"
	@echo "  make install-hooks    - Install git pre-commit hook for secret guard"
	@echo "  make ci-fast          - Fast local gate (non-mutating, smoke-focused)"
	@echo "  make ci               - Full local non-mutating pipeline"
	@echo "  knobs: CARGO_JOBS=<N> RUST_TEST_THREADS=<N> LIVE_TESTS_MODE=required|optional|skip CI_LIVE_TESTS_MODE=required|optional|skip"
	@echo "  make docker-build     - Build Docker image locally"
	@echo "  make docker-run-cli   - Run CLI in Docker container"
	@echo "  make docker-run-tui   - Run TUI in Docker container (interactive)"
	@echo "  make docker-compose-up - Start docker-compose services (Splunk)"
	@echo "  make docker-compose-cli - Run CLI via docker-compose"
	@echo "  make docker-compose-tui - Run TUI via docker-compose (interactive)"
	@echo "  make docker-clean     - Remove local Docker images"
	@echo "  make help             - Show this help message"
